/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package janken;

public class App {

    public static void main(String[] args) {
        janken.controller.JankenController controller = new janken.controller.JankenController();
        controller.jankenInfinite();
    }
}
